name          'eshamow-packer'
version       '0.1.0'
source        'https://github.com/eshamow/eshamow-packer.git'
author        'eshamow'
license       'Apache 2.0'
summary       'Maintain Hashicorp Packer installation'
description   ''
project_page  'https://github.com/eshamow/eshamow-packer'

dependency 'puppetlabs/stdlib'
